import AppKit
import Carbon
import CoreGraphics
import Foundation

/// Performs the VoiceInk-style clipboard paste:
/// snapshot pasteboard -> write transcript (+ marker types) -> synthetic Cmd-V -> restore snapshot.
@MainActor
final class PasteEngine {
    /// Private marker type; holds a per-paste UUID so we only restore the
    /// snapshot if the pasteboard still contains *our* item.
    static let sessionType = NSPasteboard.PasteboardType("com.hark.session")
    /// http://nspasteboard.org conventions — clipboard managers that honor
    /// these will skip recording our transient transcript.
    static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    private struct SnapshotItem {
        var data: [NSPasteboard.PasteboardType: Data]
        var typeOrder: [NSPasteboard.PasteboardType]
    }

    /// Full paste sequence. `releasedAt` is when the hotkey was released, used
    /// to report release -> paste-complete latency.
    func paste(text: String, releasedAt: ContinuousClock.Instant) async {
        // 4. Secure input guard: a password field (or a misbehaving app) has
        // grabbed secure event input; synthetic keyboard events would be
        // dropped or worse. Leave the text on the clipboard and bail.
        if IsSecureEventInputEnabled() {
            let pb = NSPasteboard.general
            pb.clearContents()
            pb.setString(text, forType: .string)
            print("[hark] WARNING: secure event input is enabled (a password field is focused,")
            print("       or another app holds secure input). Skipping synthetic Cmd-V.")
            print("       The text is on the clipboard — paste it manually with Cmd-V once")
            print("       secure input is released. (`ioreg -l -w0 | grep SecureInput` to find the holder.)")
            return
        }

        let pb = NSPasteboard.general
        let snapshot = snapshotPasteboard(pb)
        let sessionID = UUID().uuidString

        // Write transcript + markers as a single pasteboard item.
        pb.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        item.setData(Data(), forType: Self.transientType)
        item.setData(Data(), forType: Self.autoGeneratedType)
        item.setString(sessionID, forType: Self.sessionType)
        pb.writeObjects([item])

        // Give the pasteboard server + frontmost app's event loop a beat to
        // observe the new contents before we fire Cmd-V.
        try? await Task.sleep(for: .milliseconds(100))

        await postCommandV()

        let latency = releasedAt.duration(to: ContinuousClock.now)
        let ms = Double(latency.components.seconds) * 1000
            + Double(latency.components.attoseconds) / 1e15
        print(String(format: "[hark] pasted. release -> paste-complete: %.1f ms", ms))

        // Restore the previous clipboard after the target app has had time to
        // service the paste. Only restore if the pasteboard still holds OUR
        // session item — the user may have copied something else meanwhile.
        try? await Task.sleep(for: .milliseconds(300))
        if pb.pasteboardItems?.first?.string(forType: Self.sessionType) == sessionID {
            restore(snapshot, to: pb)
            print("[hark] previous clipboard restored (\(snapshot.count) item(s)).")
        } else {
            print("[hark] clipboard changed since paste — leaving it alone.")
        }
    }

    // MARK: - Synthetic Cmd-V

    /// Posts Cmd-V as four CGEvents from a private event source, 10 ms apart,
    /// into the HID event tap.
    private func postCommandV() async {
        let source = CGEventSource(stateID: .privateState)
        let vKey: CGKeyCode = 0x09      // kVK_ANSI_V
        let cmdKey: CGKeyCode = 0x37    // kVK_Command (left)

        let events: [(CGKeyCode, Bool, CGEventFlags)] = [
            (cmdKey, true, .maskCommand),
            (vKey, true, .maskCommand),
            (vKey, false, .maskCommand),
            (cmdKey, false, []),
        ]
        for (index, (key, down, flags)) in events.enumerated() {
            if index > 0 { try? await Task.sleep(for: .milliseconds(10)) }
            guard let event = CGEvent(
                keyboardEventSource: source, virtualKey: key, keyDown: down
            ) else { continue }
            event.flags = flags
            event.post(tap: .cghidEventTap)
        }
    }

    // MARK: - Snapshot / restore

    private func snapshotPasteboard(_ pb: NSPasteboard) -> [SnapshotItem] {
        (pb.pasteboardItems ?? []).map { item in
            var data: [NSPasteboard.PasteboardType: Data] = [:]
            for type in item.types {
                data[type] = item.data(forType: type)
            }
            return SnapshotItem(data: data, typeOrder: item.types)
        }
    }

    private func restore(_ snapshot: [SnapshotItem], to pb: NSPasteboard) {
        pb.clearContents()
        guard !snapshot.isEmpty else { return }
        let items = snapshot.map { snap -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for type in snap.typeOrder {
                if let data = snap.data[type] {
                    item.setData(data, forType: type)
                }
            }
            return item
        }
        pb.writeObjects(items)
    }
}
