// swift-tools-version: 6.0
import PackageDescription

// The Rust core is linked as a static archive produced by
// `cargo build --release -p hark-core` at the workspace root and then
// post-processed by scripts/localize-hark-core-ffi.sh into an FFI-only
// archive (only the _uniffi_/_ffi_ symbols stay exported — the raw
// staticlib's Rust std otherwise collides with the Rust std bundled in
// FluidAudio's prebuilt NemoTextProcessing xcframework: duplicate
// `_rust_eh_personality`, a hard error in debug links). The UniFFI
// bindings (Sources/Hark/Generated + Sources/hark_coreFFI) are emitted by
// scripts/build-app.sh. Build via that script, not bare `swift build`.
let harkCoreLib = "../../target/release/libhark_core_ffi.a"

let package = Package(
    name: "Hark",
    platforms: [.macOS(.v15)],
    dependencies: [
        .package(url: "https://github.com/FluidInference/FluidAudio.git", exact: "0.15.6")
    ],
    targets: [
        // C module for the UniFFI-generated FFI header (module.modulemap
        // lives here; both files are generated by scripts/build-app.sh).
        .systemLibrary(
            name: "hark_coreFFI",
            path: "Sources/hark_coreFFI"
        ),
        .executableTarget(
            name: "Hark",
            dependencies: [
                .product(name: "FluidAudio", package: "FluidAudio"),
                "hark_coreFFI",
            ],
            path: "Sources/Hark",
            linkerSettings: [
                // Hand the static archive straight to the linker so we never
                // pick up the cdylib by accident (same recipe the UniFFI
                // spike verified). Path is relative to this package dir.
                .unsafeFlags(["-Xlinker", harkCoreLib])
            ]
        ),
    ]
)
